spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded

---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:3307/basic_spring_batch?useUnicode=true&characterEncoding=utf8
    username: root
    password: mariadb
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
